[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
claim_tokens = "52zV7g7WwxLu93W9dxrTr1dvZWD9ZAs7tXHoLASaP6p5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/maksym/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
